### ISSUE TITLE
Implement logout

### ISSUE THREAD

**Issue by popand** [popand/webclient#3]
![image](https://cloud.githubusercontent.com/assets/637144/11387582/e75705c0-92f9-11e5-87f3-32c82304df0a.png)

![image](https://cloud.githubusercontent.com/assets/637144/11387663/d91f88c8-92fa-11e5-89f3-8688446a3bd7.png)

Please implement logout using the following api:

http://54.165.55.11:8765/customerservice/v1/customer/logout

Also if possible to update the css to have line up with the rest of the text as currently its been pushed to the next line

**Comment by meowcoder** [comment]
It's pushed to the next line because the user name is too long (longer than "Anthony Stevens"), something will have to go away (get hidden) if you want the user name to be on the same line.

But then user name can potentially get even longer, I propose to show just an icon and the username goes to the dropdown.

Or alternatively truncate it: "customer1@fir..."

**Comment by popand** [comment]
In that case please remove `Extreme Channel` and `Clips`

![image](https://cloud.githubusercontent.com/assets/637144/11389494/59760326-930f-11e5-8631-4dae030813cc.png)
